/*
 * Created on 22.05.2004
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */
package de.uniessen.wiinf.wip.tree;

/**
 * @author Jonas Sprenger
 *
 * TODO To change the template for this generated type comment go to
 * Window - Preferences - Java - Code Generation - Code and Comments
 */

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import de.uniessen.wiinf.wip.internationalisation.Internationalization;

public class RenameDialog extends javax.swing.JDialog
						implements KeyListener {
    
    boolean isOK = false;
    /** Creates new form RenameDialog */
    public RenameDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        addKeyListener(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        text = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cancel = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setTitle(Internationalization.getMessage("rename"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        text.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        text.setMinimumSize(new java.awt.Dimension(100, 20));
        text.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel1.add(text);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cancel.setText(Internationalization.getMessage("Cancel"));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jPanel2.add(cancel);

        ok.setText(Internationalization.getMessage("OK"));
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jPanel2.add(ok);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jLabel1.setText(Internationalization.getMessage(
			"please_enter_a_name:"));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel3.add(jLabel1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        isOK = true;
        setVisible(false);
    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
    }//GEN-LAST:event_closeDialog
    
    public String getNewName(){
        return text.getText();
    }
    
    public void setNewName(String name){
        text.setText(name);
    }
    
    public boolean isOK(){
    return isOK;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new RenameDialog(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text;
    private javax.swing.JButton ok;
    private javax.swing.JLabel jLabel1;
	/* (non-Javadoc)
	 * @see java.awt.event.KeyListener#keyTyped(java.awt.event.KeyEvent)
	 */
	public void keyTyped(KeyEvent e) {
		keyPressed(e);
		
	}

	/* (non-Javadoc)
	 * @see java.awt.event.KeyListener#keyPressed(java.awt.event.KeyEvent)
	 */
	public void keyPressed(KeyEvent e) {
		if (e.getKeyCode() == KeyEvent.VK_ENTER){
			isOK = true;
			setVisible(false);
		}
		else if (e.getKeyCode() == KeyEvent.VK_ESCAPE){
			setVisible(false);
	}
			
		
	}

	/* (non-Javadoc)
	 * @see java.awt.event.KeyListener#keyReleased(java.awt.event.KeyEvent)
	 */
	public void keyReleased(KeyEvent e) {
		keyPressed(e);
		
	}
    // End of variables declaration//GEN-END:variables
    
}
